---
title: "Untitlgyvuged"
output: html_document
---

1. Dataset preparations
```{r}
library(GEOquery)
library(tidyverse)
library(ComplexHeatmap)
library(factoextra)
library(ggrepel)
library(GGally)
```
1.1 Load GEO data
```{r}
gse <- getGEO("GSE163151")
```
1.2 Extract metadata
```{r}
metadata <- pData(gse$GSE163151_series_matrix.txt.gz)
```
1.3 Check metadata structure
```{r}
dim(metadata)
colnames(metadata)
head(metadata)
```
1.4 Check sample titles
```{r}
head(metadata$title, 20)
```
1.5 Check sample type
```{r}
table(metadata$source_name_ch1)
```
1.6 Find all characteristics columns
```{r}
char_cols <- grep(
  "characteristics_ch1",
  colnames(metadata),
  value = TRUE
)

char_cols
```
1.7 Print unique values in each characteristics column
```{r}
for(col in char_cols){
  cat("\n---", col, "---\n")
  print(unique(metadata[[col]]))
}
```
2. Metadata preparation
```{r}
metadata_clean <- metadata |>
  transmute(
    geo_accession = geo_accession,
    sample_name = title,
    sample_type = source_name_ch1,

    disease_group = str_remove(
      characteristics_ch1.1,
      "^disease state: "
    ),

    pathogen = str_remove(
      characteristics_ch1.2,
      "^pathogen: "
    ),

    severity = str_remove(
      characteristics_ch1.4,
      "^disease severity: "
    )
  ) |>
  separate(
    sample_name,
    into = c("sample_prefix", "sample_number"),
    sep = "-",
    remove = FALSE
  )

head(metadata_clean)
```
2.1 Check separated sample names
```{r}
head(
  metadata_clean |>
    select(
      sample_name,
      sample_prefix,
      sample_number
    )
)
```
2.2 Create analysis groups
```{r}
metadata_np <- metadata_clean |>
  filter(sample_type == "NP swab") |>
  mutate(
    analysis_group = case_when(
      disease_group == "COVID-19" ~ "COVID-19",
      disease_group == "Viral acute respiratory illness" ~ "Other Virus",
      disease_group == "Donor control" ~ "Healthy",
      disease_group == "Non-viral acute respiratory illness" ~ "Nonviral",
      TRUE ~ "Exclude"
    )
  )

table(metadata_np$analysis_group)

table(
  metadata_np$analysis_group,
  metadata_np$pathogen
)
```
3. Main comparison metadata
```{r}
metadata_main <- metadata_np |>
  filter(
    analysis_group %in% c("COVID-19", "Other Virus")
  )

table(metadata_main$analysis_group)
```
3.1 Check main comparison metadata
```{r}
head(metadata_main)

table(
  metadata_main$analysis_group,
  metadata_main$pathogen
)
```
